### ISSUE TITLE
Mk48: Positive Y is up/north

### ISSUE THREAD

**Issue by finnbear** [FedorLap2006/WarriorAI#1]
Unlike image libraries where positive Y tends to be down.

A good way to check is that the tiny islands should be at the bottom/south.

**Comment by FedorLap2006** [comment]
Thanks for the report.

P.S. Code isn't public yet, but going to publish it pretty soon.

**Comment by FedorLap2006** [comment]
Published changes with the fix in d83736ab4b474bc45a6ff2a55325941058351719
